name: Bug report
description: File a bug report
labels: ["bug"]

body:
  - type: markdown
    attributes: 
      value: |
        Remember to check that your bug hasn't already been reported! 
        Note that specific mod bugs do *not* go here, and go to the appropriate mod's repository.
  - type: input
    id: chrysalis-version
    attributes:
      label: Chrysalis Version
      description: "The version of Chrysalis you're using"
      placeholder: "v0.1.0"
    validations:
      required: true
  - type: input
    id: silksong-version
    attributes:
      label: Hollow Knight: Silksong Version
      description: "The version of Hollow Knight: Silksong you're using, indicated in the bottom right of the title screen."
      placeholder: "v1.0.0.0"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: What can someone do to experience the bug you observed?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Attach any logs, if any, here. You can find logs in `~/.config/Chrysalis` or `%appdata%\Chrysalis`. There may also be logs in the same folder as the `.exe` or `.app` If there are no logs, please write 'None' here. Note that in any case where the app crashed or indicated an error or exception there *will* be logs you should include located in the previously mentioned folder.
    validations:
      required: true
